# Generated by Django 5.2.8 on 2026-09-28 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_practic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='academic_degree',
        ),
    ]
