# Generated by Django 6.0.3 on 2026-10-04 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_practic', '0003_group_alter_student_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group_number',
        ),
    ]
